# Generated by Django 4.1.2 on 2022-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_available',
            field=models.BooleanField(default=True),
        ),
    ]
