# Generated by Django 4.1.2 on 2023-01-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_filter',
            name='price',
            field=models.CharField(choices=[('0 to 50', '0 to 50'), ('50 to 100', '50 to 100'), ('100 to 150', '100 to 150'), ('150 to 200', '150 to 200'), ('200 to 250', '200 to 250'), ('250 to 500', '250 to 500'), ('500+', '500+')], max_length=50),
        ),
    ]
