# Generated by Django 4.1.2 on 2023-01-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='813BB', editable=False, max_length=50),
        ),
    ]
