# Generated by Django 4.1.2 on 2023-01-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
