# Generated by Django 4.1.2 on 2023-01-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='image',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
