# Generated by Django 4.1.2 on 2023-01-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='image',
        ),
    ]
