# Generated by Django 4.1.2 on 2023-01-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Order accepted for realization', 'Order accepted for realization'), ('Order shipped', 'Order shipped'), ('Completed', 'Completed')], default='Order placed', max_length=60, null=True),
        ),
    ]
